blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views


app_name = 'blog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.ablog, name='ablog'),
    path('<int:blog_id>', views.detail, name='detail'),
]

portfol/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfol/', include('portfol.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class myblogs(models.Model):
    title = models.CharField(max_length = 200)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfol/models.py
from django.db import models

# Create your models here.

class project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='images/portfol')
    url = models.URLField(blank = True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import myblogs

# Create your views here.



def ablog(request):
    blogs = myblogs.objects.order_by('-date')
    return render(request,'blog.html', {'blogs' : blogs})


def detail(request,blog_id):
    blog = get_object_or_404(myblogs, pk=blog_id)
    return render(request, 'ind_blog.html', {'blog' : blog})

portfol/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import project

# Create your views here.

def home(request):
    projects = project.objects.all()
    return render(request,'home.html', {'projects' : projects})

templates/blog.html
{% extends 'navbar.html' %}

{% block content %}

    <h1 class="font-weight-bold text-center">Blog</h1>
    <h3 class="text-center mb-5">Rinku has written {{blogs.count}} blog{{blogs.count|pluralize}}</h3>
    {% for bl in blogs %}

    <div class="row justify justify-content-center my-3">

      <div class="col-md-10">

        <a href="{% url 'blog:detail' bl.id %}"> <h1> {{bl.title}}</h1></a>

        <h5>{{bl.date|date:'M d Y'}}</h5>

        <h4>{{bl.description|striptags|truncatechars:100}}</h4>

      </div>

    </div>

    {% endfor %}

    {% endblock %}

templates/home.html
{% extends 'navbar.html' %}

{% block content %}

{% load static %}

<div class="row justify-content-center my-3">

  <div class="col-5">

  <img src="{% static 'portfol/pic.jpg' %}" height="170" width="420" class="img-fluid">

</div>

  </div>


  <div class="row justify-content-center mb-3">

    <div class="col-9 text-center">

        <h1 <col span="font_weight-bold">This website is made my Me</h1>

    </div>

  </div>

  <h2 class="mt-5">Projects</h2>




    <div class="row">

      {% for p in projects  %}

      <div class="col-lg-4 col-md-6">

        {% if p.url %}

        <a href="{{p.url}}">
          <img src="{{p.image.url}}" class="image-fluid mb-2" height="170" width="320">
        </a>

        {% else %}
        <img src="{{p.image.url}}" class="image-fluid mb-2">

        {% endif %}

        <h3>{{p.title}}</h3>
        <p>{{p.description}}</p>

      </div>

      {% endfor %}

    </div>

{% endblock %}

templates/ind_blog.html
{% extends 'navbar.html' %}

{% block content %}

    <h1 class="text-center mt-5">{{blog.title}}</h1>

    <h5 class="text-center mb-5 text-muted">{{blog.date|date:'F jS Y'}}</h5>

    <p>{{blog.description|safe}}</p>

    {% endblock  %}

templates/navbar.html
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <link rel="icon" type="image" href="{% static "portfol/person.png" %}">
    <title>Portfolio</title>
  </head>
  <body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static "portfol/person.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span>Home</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% static 'portfol/resume.pdf' %}">Resume</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.Facebook.com" target="_blank">Facebook</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.linkedin.com/" target="_blank">Linkedin</a>
            </li>
            <li>
              <a role="button" href="{% url 'blog:ablog' %}" class=" mt-2 badge badge-primary">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>